version: '3.8'
services:
    postgres:
        image: postgres:16.2-alpine3.19
        environment:
            - POSTGRES_USER=mrosario
            - POSTGRES_PASSWORD=mysecretpassword
            - PGPASSWORD=mysecretpassword
            - POSTGRES_DB=piscineds
        volumes:
            - postgres-db-volume:/var/lib/postgresql/data
        ports:
            - 5432:5432
        networks:
            - postgres-db-network
    pgadmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: 'mrosario@student.42madrid.com'
            PGADMIN_DEFAULT_PASSWORD: 'mysecretpassword'
        ports:
            - 16543:80
        volumes:
            - ./servers.json:/pgadmin4/servers.json
        networks:
            - postgres-db-network

volumes:
    postgres-db-volume:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ../data
networks:
    postgres-db-network:
        driver: bridge
